### PR TITLE
Standardise project structure

### PR DESCRIPTION
**Pull request by Pathoschild**
The project structure is a bit complicated and non-standard.

This pull request...
* copies the mod into the game's `Mods` folder automatically on build;
* removes custom build configurations and assembly attributes;
* simplifies `TimeSpeed.csproj` and `.gitignore`;
* switches Json.NET to the version used by SMAPI;
* targets .NET Framework 4.5 for crossplatform compatibility;
* exports `.pdb` files in release builds;
* removes logic that blocks SMAPI when running a debug build without a debugger attached;
* and updates the readme to document the simplified crossplatform build steps.

This is part I of the update to the latest SMAPI interfaces; let me know if you disagree with any of the changes.

### CODE REVIEW

**Comment by alexb5dh** [comment]
Thanks. Everything looks perfect.

**Comment by alexb5dh** [comment]
Actually, @Pathoschild, how can I build mod for Linux or Mac while being on Windows with new build config? Previously I copied platform specific binaries to internal directory.
Did I miss it in [config](https://github.com/Pathoschild/Stardew.ModBuildConfig#readme) doc?

**Comment by Pathoschild** [comment]
@alexb5dh You don't need to anymore. Just build it once on Windows, and SMAPI will rewrite it automatically when it's loaded on Linux/Mac. :)

**Comment by alexb5dh** [comment]
That sounds really awesome! Can you point me to the SMAPI code where this magic is done?

**Comment by Pathoschild** [comment]
The magic happens [in SMAPI's `AssemblyLoader`](https://github.com/Pathoschild/SMAPI/blob/1.8/src/StardewModdingAPI/Framework/AssemblyLoader.cs#L56-L92), which reads the assemblies with Mono.Cecil and rewrites them for compatibility if needed.

**Pull request merged**
