### PR TITLE
Update to latest SMAPI & refactor

### PR DESCRIPTION
**Pull request by Pathoschild**
This pull request...

* migrates to the latest SMAPI APIs (which lets us simplify the config and logging code quite a bit);
* marks all internal classes internal;
* copyedits & adds missing code documentation;
* applies .NET best practices (e.g. one class per file);
* applies SMAPI best practices (e.g. avoid lambdas as event handlers);
* removes now-unused dependencies on Json.NET and the MSBuild extensions pack.

### CODE REVIEW

**Comment by alexb5dh** [comment]
Big thanks for refactoring and documentation.
Will check this in game and publish a new release in a few days.

**Comment by alexb5dh** [comment]
Looks like Json.NET reference removal was too early since Keys serialization as string will only be added in 1.9.

**Comment by Pathoschild** [comment]
The previous version works fine with SMAPI 1.8; how about releasing this as the SMAPI 1.9 / Stardew Valley 1.2 version?

**Comment by alexb5dh** [comment]
I'm all for it. Are there any estimation dates for 1.2?

**Comment by Pathoschild** [comment]
Not that I know of, but development and feedback is slowing down so I'd guess within the next week or two.

**Comment by alexb5dh** [comment]
Ok, I'll keep track of the news then.

**Pull request merged**
